export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'film', label: 'Film Stocks', icon: '🎞️' },
  { id: '90s', label: '90s Camera', icon: '📷' },
  { id: '2000s', label: '2000s Digital', icon: '📱' },
  { id: 'disposable', label: 'Disposable', icon: '🎞️' },
  { id: 'compression', label: 'Compression', icon: '💾' },
  { id: 'glitch', label: 'Glitch Art', icon: '📺' },
  { id: 'color', label: 'Color/Tone', icon: '🌈' },
  { id: 'lens', label: 'Lens FX', icon: '🔍' },
  { id: 'texture', label: 'Texture', icon: '🎨' },
];

export const PRESETS = [
  // Film Stocks
  { id:'kodak_gold_200', name:'Kodak Gold 200', cat:'film', fx:{brightness:5,contrast:8,saturation:15,temperature:12,grain:15,vignette:10,fade:5} },
  { id:'kodak_gold_400', name:'Kodak Gold 400', cat:'film', fx:{brightness:3,contrast:10,saturation:20,temperature:15,grain:20,vignette:12,fade:3} },
  { id:'kodak_portra_160', name:'Portra 160', cat:'film', fx:{brightness:8,contrast:5,saturation:-5,temperature:8,grain:10,fade:8} },
  { id:'kodak_portra_400', name:'Portra 400', cat:'film', fx:{brightness:5,contrast:8,saturation:5,temperature:10,grain:15,fade:5} },
  { id:'kodak_portra_800', name:'Portra 800', cat:'film', fx:{brightness:3,contrast:12,saturation:8,temperature:12,grain:25,fade:3} },
  { id:'kodak_ektar', name:'Kodak Ektar 100', cat:'film', fx:{brightness:5,contrast:15,saturation:25,temperature:5,grain:8,vignette:5} },
  { id:'kodak_colorplus', name:'Kodak ColorPlus', cat:'film', fx:{brightness:8,contrast:5,saturation:12,temperature:18,grain:18,fade:10} },
  { id:'fuji_superia_400', name:'Fuji Superia 400', cat:'film', fx:{brightness:3,contrast:10,saturation:10,temperature:-8,tint:5,grain:18,fade:5} },
  { id:'fuji_superia_800', name:'Fuji Superia 800', cat:'film', fx:{brightness:0,contrast:12,saturation:15,temperature:-5,grain:25,fade:3} },
  { id:'fuji_superia_1600', name:'Fuji Superia 1600', cat:'film', fx:{brightness:-3,contrast:15,saturation:8,temperature:-5,grain:35,fade:5} },
  { id:'fuji_pro400h', name:'Fuji Pro 400H', cat:'film', fx:{brightness:8,contrast:3,saturation:-8,temperature:-3,tint:3,grain:12,fade:10} },
  { id:'fuji_velvia', name:'Fuji Velvia 50', cat:'film', fx:{brightness:0,contrast:20,saturation:35,temperature:3,grain:8} },
  { id:'fuji_provia', name:'Fuji Provia 100F', cat:'film', fx:{brightness:3,contrast:12,saturation:18,temperature:0,grain:8} },
  { id:'agfa_vista_200', name:'Agfa Vista 200', cat:'film', fx:{brightness:5,contrast:8,saturation:12,temperature:10,grain:20,fade:8} },
  { id:'agfa_vista_400', name:'Agfa Vista 400', cat:'film', fx:{brightness:3,contrast:12,saturation:15,temperature:12,grain:28,fade:5} },
  { id:'cinestill_800t', name:'CineStill 800T', cat:'film', fx:{brightness:-3,contrast:15,saturation:10,temperature:-15,grain:20,halation:30} },
  { id:'ilford_hp5', name:'Ilford HP5+', cat:'film', fx:{brightness:0,contrast:15,saturation:-100,grain:22,fade:5} },
  { id:'ilford_delta3200', name:'Ilford Delta 3200', cat:'film', fx:{brightness:-5,contrast:20,saturation:-100,grain:40,fade:3} },
  { id:'kodak_trix', name:'Kodak Tri-X 400', cat:'film', fx:{brightness:3,contrast:18,saturation:-100,grain:25,fade:5} },
  { id:'kodak_tmax', name:'Kodak T-Max 400', cat:'film', fx:{brightness:0,contrast:12,saturation:-100,grain:15,fade:3} },
  { id:'cross_process_1', name:'Cross Process I', cat:'film', fx:{brightness:5,contrast:20,saturation:25,temperature:-20,tint:15,grain:15,vignette:15} },
  { id:'cross_process_2', name:'Cross Process II', cat:'film', fx:{brightness:3,contrast:18,saturation:30,temperature:20,tint:-10,grain:18,vignette:12} },
  { id:'expired_kodak', name:'Expired Kodak', cat:'film', fx:{brightness:8,contrast:-5,saturation:-15,temperature:20,grain:30,fade:25,vignette:15} },
  { id:'expired_fuji', name:'Expired Fuji', cat:'film', fx:{brightness:5,contrast:-3,saturation:-10,temperature:-15,tint:10,grain:28,fade:22} },
  { id:'push_2_stops', name:'Push +2 Stops', cat:'film', fx:{brightness:-10,contrast:25,saturation:5,grain:35} },
  { id:'pull_1_stop', name:'Pull -1 Stop', cat:'film', fx:{brightness:10,contrast:-8,saturation:-5,grain:10,fade:8} },
  // 90s Cameras
  { id:'canon_sureshot', name:'Canon Sure Shot', cat:'90s', fx:{brightness:5,contrast:5,saturation:8,sharpness:-10,vignette:18,grain:12,temperature:5} },
  { id:'olympus_stylus', name:'Olympus mju-II', cat:'90s', fx:{brightness:3,contrast:10,saturation:12,sharpness:-5,vignette:15,grain:10} },
  { id:'yashica_t4', name:'Yashica T4', cat:'90s', fx:{brightness:5,contrast:12,saturation:15,sharpness:5,vignette:12,grain:12} },
  { id:'nikon_l35af', name:'Nikon L35AF', cat:'90s', fx:{brightness:3,contrast:8,saturation:10,sharpness:-8,vignette:20,grain:15,temperature:3} },
  { id:'contax_t2', name:'Contax T2', cat:'90s', fx:{brightness:5,contrast:15,saturation:18,sharpness:8,vignette:8,grain:10} },
  { id:'ricoh_gr1', name:'Ricoh GR1', cat:'90s', fx:{brightness:0,contrast:12,saturation:8,sharpness:10,vignette:10,grain:12} },
  { id:'90s_flash', name:'90s Flash Shot', cat:'90s', fx:{brightness:20,contrast:15,saturation:-5,sharpness:-15,vignette:30,grain:15,temperature:10} },
  { id:'90s_redeye', name:'90s Red Eye', cat:'90s', fx:{brightness:15,contrast:12,saturation:5,sharpness:-12,vignette:25,grain:12,temperature:8} },
  { id:'90s_lowlight', name:'90s Low Light', cat:'90s', fx:{brightness:-15,contrast:5,saturation:-10,grain:40,vignette:20,blur:5} },
  { id:'90s_overexposed', name:'90s Overexposed', cat:'90s', fx:{brightness:25,contrast:-5,saturation:-8,grain:15,fade:15} },
  { id:'90s_underexposed', name:'90s Underexposed', cat:'90s', fx:{brightness:-20,contrast:8,saturation:-12,grain:25,vignette:20} },
  { id:'90s_polaroid', name:'90s Polaroid', cat:'90s', fx:{brightness:8,contrast:5,saturation:-10,temperature:15,grain:10,fade:15,vignette:5} },
  // 2000s Digital
  { id:'sony_cybershot', name:'Sony Cybershot', cat:'2000s', fx:{brightness:5,contrast:8,saturation:18,sharpness:20,temperature:-5,grain:3} },
  { id:'canon_powershot', name:'Canon PowerShot', cat:'2000s', fx:{brightness:3,contrast:10,saturation:15,sharpness:25,temperature:3,grain:5} },
  { id:'fuji_finepix', name:'Fuji FinePix', cat:'2000s', fx:{brightness:5,contrast:5,saturation:20,sharpness:15,temperature:-8,grain:5} },
  { id:'kodak_easyshare', name:'Kodak EasyShare', cat:'2000s', fx:{brightness:8,contrast:5,saturation:12,sharpness:10,temperature:10,grain:5,fade:5} },
  { id:'nikon_coolpix', name:'Nikon Coolpix', cat:'2000s', fx:{brightness:3,contrast:12,saturation:15,sharpness:22,temperature:0,grain:3} },
  { id:'olympus_camedia', name:'Olympus Camedia', cat:'2000s', fx:{brightness:5,contrast:8,saturation:10,sharpness:18,temperature:-3,grain:5} },
  { id:'2000s_640x480', name:'640x480 Mode', cat:'2000s', fx:{brightness:3,contrast:5,saturation:8,sharpness:30,grain:8,pixelate:8} },
  { id:'2000s_1mp', name:'1.3 Megapixel', cat:'2000s', fx:{brightness:3,contrast:8,saturation:12,sharpness:25,grain:5,pixelate:4} },
  { id:'2000s_2mp', name:'2 Megapixel', cat:'2000s', fx:{brightness:3,contrast:10,saturation:15,sharpness:20,grain:3,pixelate:2} },
  { id:'2000s_flash', name:'2000s Flash', cat:'2000s', fx:{brightness:25,contrast:18,saturation:5,sharpness:15,temperature:5,grain:3} },
  { id:'2000s_nightmode', name:'Night Mode 2003', cat:'2000s', fx:{brightness:-10,contrast:5,saturation:-15,sharpness:10,grain:20,blur:3} },
  { id:'2000s_macro', name:'Macro Mode', cat:'2000s', fx:{brightness:5,contrast:12,saturation:20,sharpness:30,vignette:15,grain:3} },
  { id:'2000s_purple_fringe', name:'Purple Fringing', cat:'2000s', fx:{brightness:5,contrast:10,saturation:12,sharpness:25,chromatic:20,grain:3} },
  { id:'2000s_ccd_bloom', name:'CCD Bloom', cat:'2000s', fx:{brightness:10,contrast:5,saturation:15,sharpness:15,halation:25,grain:3} },
  { id:'webcam_2004', name:'Webcam 2004', cat:'2000s', fx:{brightness:-5,contrast:5,saturation:-20,sharpness:-10,grain:25,pixelate:10,blur:5} },
  { id:'phonecam_2005', name:'Phone Cam 2005', cat:'2000s', fx:{brightness:-3,contrast:8,saturation:-10,sharpness:-15,grain:20,pixelate:6,blur:3} },
  // Disposable
  { id:'kodak_funsaver', name:'Kodak FunSaver', cat:'disposable', fx:{brightness:5,contrast:8,saturation:12,temperature:15,grain:25,vignette:30,fade:8,sharpness:-15} },
  { id:'kodak_funsaver_flash', name:'FunSaver + Flash', cat:'disposable', fx:{brightness:20,contrast:15,saturation:5,temperature:12,grain:22,vignette:35,sharpness:-12} },
  { id:'fuji_quicksnap', name:'Fuji QuickSnap', cat:'disposable', fx:{brightness:3,contrast:10,saturation:15,temperature:-5,tint:5,grain:28,vignette:25,fade:5,sharpness:-18} },
  { id:'fuji_quicksnap_flash', name:'QuickSnap + Flash', cat:'disposable', fx:{brightness:22,contrast:18,saturation:8,temperature:-3,grain:25,vignette:30,sharpness:-15} },
  { id:'agfa_lebox', name:'Agfa LeBox', cat:'disposable', fx:{brightness:5,contrast:5,saturation:8,temperature:18,grain:30,vignette:28,fade:12,sharpness:-20} },
  { id:'ilford_hp5_disp', name:'Ilford HP5 Disp', cat:'disposable', fx:{brightness:0,contrast:18,saturation:-100,grain:35,vignette:25,sharpness:-15} },
  { id:'disp_underwater', name:'Underwater Disp', cat:'disposable', fx:{brightness:-5,contrast:5,saturation:-15,temperature:-20,grain:30,vignette:35,blur:5,sharpness:-20} },
  { id:'disp_lightleak_1', name:'Light Leak I', cat:'disposable', fx:{brightness:8,contrast:5,saturation:10,temperature:10,grain:25,vignette:20,lightleak:40} },
  { id:'disp_lightleak_2', name:'Light Leak II', cat:'disposable', fx:{brightness:5,contrast:8,saturation:12,temperature:-5,grain:22,vignette:25,lightleak:60} },
  { id:'disp_lightleak_3', name:'Light Leak III', cat:'disposable', fx:{brightness:10,contrast:3,saturation:8,temperature:15,grain:28,vignette:18,lightleak:80} },
  { id:'disp_double_exp', name:'Double Exposure', cat:'disposable', fx:{brightness:10,contrast:-5,saturation:-10,grain:20,vignette:15,fade:20} },
  { id:'disp_90s_party', name:'90s Party', cat:'disposable', fx:{brightness:15,contrast:12,saturation:20,temperature:10,grain:22,vignette:30,lightleak:30} },
  { id:'disp_2000s_grad', name:'2000s Graduation', cat:'disposable', fx:{brightness:10,contrast:8,saturation:10,temperature:8,grain:20,vignette:25,fade:5} },
  { id:'disp_scratched', name:'Scratched Film', cat:'disposable', fx:{brightness:3,contrast:10,saturation:5,grain:30,vignette:20,scratches:40} },
  { id:'disp_burned', name:'Burned Edges', cat:'disposable', fx:{brightness:5,contrast:15,saturation:-5,grain:25,vignette:50,temperature:20} },
  // Compression
  { id:'jpeg_q10', name:'JPEG Quality 10', cat:'compression', fx:{jpegQ:10} },
  { id:'jpeg_q20', name:'JPEG Quality 20', cat:'compression', fx:{jpegQ:20} },
  { id:'jpeg_q30', name:'JPEG Quality 30', cat:'compression', fx:{jpegQ:30} },
  { id:'jpeg_q50', name:'JPEG Quality 50', cat:'compression', fx:{jpegQ:50} },
  { id:'jpeg_double', name:'Double Compressed', cat:'compression', fx:{jpegQ:30,jpegPasses:2} },
  { id:'jpeg_triple', name:'Triple Compressed', cat:'compression', fx:{jpegQ:25,jpegPasses:3} },
  { id:'jpeg_nuke', name:'JPEG Nuke', cat:'compression', fx:{jpegQ:5,jpegPasses:2} },
  { id:'gif_256', name:'GIF 256 Colors', cat:'compression', fx:{colorReduce:256,dither:true} },
  { id:'gif_16', name:'GIF 16 Colors', cat:'compression', fx:{colorReduce:16,dither:true} },
  { id:'gif_4', name:'GIF 4 Colors', cat:'compression', fx:{colorReduce:4,dither:true} },
  { id:'gif_2', name:'GIF 2 Colors', cat:'compression', fx:{colorReduce:2,dither:true} },
  { id:'gif_nodither', name:'No Dither 16', cat:'compression', fx:{colorReduce:16,dither:false} },
  { id:'56k_web', name:'56K Web Image', cat:'compression', fx:{jpegQ:15,pixelate:3,saturation:-10} },
  { id:'geocities', name:'GeoCities Era', cat:'compression', fx:{jpegQ:20,pixelate:2,saturation:-5,sharpness:20} },
  { id:'myspace_2006', name:'MySpace 2006', cat:'compression', fx:{jpegQ:40,saturation:10,contrast:15,sharpness:15} },
  { id:'ig_2012', name:'Instagram 2012', cat:'compression', fx:{jpegQ:60,saturation:15,contrast:10,vignette:10} },
  { id:'fb_2008', name:'Facebook 2008', cat:'compression', fx:{jpegQ:45,saturation:-5,sharpness:10} },
  { id:'deepfried', name:'Deep Fried', cat:'compression', fx:{jpegQ:5,contrast:40,saturation:40,sharpness:50} },
  { id:'needs_more_jpeg', name:'Needs More JPEG', cat:'compression', fx:{jpegQ:3,jpegPasses:4,sharpness:30} },
  { id:'bitmap_256', name:'Bitmap 256', cat:'compression', fx:{colorReduce:256,dither:false,pixelate:2} },
  // Glitch Art
  { id:'rgb_shift', name:'RGB Shift', cat:'glitch', fx:{channelShift:15} },
  { id:'rgb_split_heavy', name:'RGB Split Heavy', cat:'glitch', fx:{channelShift:40} },
  { id:'scanlines', name:'Scan Lines', cat:'glitch', fx:{scanlines:50} },
  { id:'scanlines_heavy', name:'CRT Heavy', cat:'glitch', fx:{scanlines:80,brightness:-5,contrast:10} },
  { id:'vhs_tracking', name:'VHS Tracking', cat:'glitch', fx:{scanlines:30,channelShift:8,grain:15,blur:3} },
  { id:'vhs_pause', name:'VHS Pause', cat:'glitch', fx:{scanlines:60,channelShift:20,grain:25,blur:5} },
  { id:'pixel_sort_h', name:'Pixel Sort H', cat:'glitch', fx:{pixelSort:'horizontal'} },
  { id:'pixel_sort_v', name:'Pixel Sort V', cat:'glitch', fx:{pixelSort:'vertical'} },
  { id:'datamosh_light', name:'Datamosh Light', cat:'glitch', fx:{datamosh:30} },
  { id:'datamosh_heavy', name:'Datamosh Heavy', cat:'glitch', fx:{datamosh:70} },
  { id:'bit_8', name:'8-Bit Color', cat:'glitch', fx:{bitDepth:8,pixelate:3} },
  { id:'bit_4', name:'4-Bit Color', cat:'glitch', fx:{bitDepth:4,pixelate:4} },
  { id:'bit_2', name:'2-Bit Color', cat:'glitch', fx:{bitDepth:2,pixelate:5} },
  { id:'bit_1', name:'1-Bit B&W', cat:'glitch', fx:{bitDepth:1,pixelate:3,saturation:-100} },
  { id:'broken_lcd', name:'Broken LCD', cat:'glitch', fx:{channelShift:25,scanlines:40,brightness:-10,contrast:20} },
  { id:'digital_rain', name:'Digital Rain', cat:'glitch', fx:{scanlines:20,channelShift:5,grain:10,temperature:-15} },
  { id:'signal_loss', name:'Signal Loss', cat:'glitch', fx:{scanlines:50,channelShift:30,grain:30,blur:8} },
  { id:'corruption', name:'Data Corruption', cat:'glitch', fx:{datamosh:50,channelShift:15,grain:20} },
  { id:'tv_static', name:'TV Static', cat:'glitch', fx:{grain:80,contrast:20,saturation:-100} },
  { id:'macroblock', name:'Macroblocking', cat:'glitch', fx:{pixelate:12,jpegQ:15,contrast:10} },
  // Color/Tone
  { id:'sepia', name:'Sepia', cat:'color', fx:{saturation:-100,temperature:30,contrast:5,fade:10} },
  { id:'cyanotype', name:'Cyanotype', cat:'color', fx:{saturation:-100,temperature:-35,contrast:15,fade:5} },
  { id:'platinum', name:'Platinum Print', cat:'color', fx:{saturation:-100,contrast:8,fade:15,brightness:5} },
  { id:'lomo_1', name:'Lomo LC-A', cat:'color', fx:{contrast:20,saturation:30,vignette:30,temperature:5,grain:12} },
  { id:'lomo_2', name:'Lomo Purple', cat:'color', fx:{contrast:18,saturation:25,vignette:25,tint:20,grain:15} },
  { id:'infrared', name:'Infrared Film', cat:'color', fx:{saturation:-60,temperature:-10,tint:30,contrast:15,grain:20} },
  { id:'thermal', name:'Thermal Camera', cat:'color', fx:{thermal:true} },
  { id:'nightvision', name:'Night Vision', cat:'color', fx:{saturation:-100,temperature:-20,tint:40,brightness:15,grain:25,scanlines:10} },
  { id:'duotone_amber', name:'Duotone Amber', cat:'color', fx:{saturation:-100,temperature:25,contrast:10} },
  { id:'duotone_cyan', name:'Duotone Cyan', cat:'color', fx:{saturation:-100,temperature:-25,contrast:10} },
  { id:'duotone_pink', name:'Duotone Pink', cat:'color', fx:{saturation:-100,tint:30,temperature:5,contrast:10} },
  { id:'faded_vintage', name:'Faded Vintage', cat:'color', fx:{saturation:-25,fade:30,brightness:5,contrast:-5,temperature:8} },
  { id:'bleach_bypass', name:'Bleach Bypass', cat:'color', fx:{saturation:-40,contrast:25,grain:10} },
  { id:'orange_teal', name:'Orange & Teal', cat:'color', fx:{saturation:20,temperature:10,contrast:12,tint:-5} },
  { id:'muted_pastel', name:'Muted Pastel', cat:'color', fx:{saturation:-20,brightness:10,contrast:-10,fade:15} },
  // Lens FX
  { id:'tiltshift', name:'Tilt Shift', cat:'lens', fx:{tiltshift:true} },
  { id:'fisheye', name:'Fisheye', cat:'lens', fx:{fisheye:30} },
  { id:'barrel', name:'Barrel Distort', cat:'lens', fx:{barrel:20} },
  { id:'pincushion', name:'Pincushion', cat:'lens', fx:{barrel:-20} },
  { id:'chromatic_subtle', name:'Chromatic Subtle', cat:'lens', fx:{chromatic:8} },
  { id:'chromatic_heavy', name:'Chromatic Heavy', cat:'lens', fx:{chromatic:25} },
  { id:'soft_focus', name:'Soft Focus', cat:'lens', fx:{blur:8,brightness:5,contrast:-3} },
  { id:'vaseline', name:'Vaseline Lens', cat:'lens', fx:{blur:12,brightness:8,contrast:-5,vignette:15} },
  { id:'bokeh_circle', name:'Bokeh Circle', cat:'lens', fx:{blur:15,brightness:3} },
  { id:'holga', name:'Holga', cat:'lens', fx:{vignette:40,blur:8,saturation:15,contrast:10,grain:20} },
  { id:'toy_camera', name:'Toy Camera', cat:'lens', fx:{vignette:35,saturation:25,contrast:15,sharpness:-10,grain:15} },
  { id:'prism', name:'Prism Effect', cat:'lens', fx:{channelShift:12,brightness:5} },
  { id:'lens_flare', name:'Lens Flare', cat:'lens', fx:{brightness:8,contrast:5,lightleak:20} },
  { id:'anamorphic', name:'Anamorphic', cat:'lens', fx:{brightness:5,lightleak:15,contrast:8} },
  // Texture/Aging
  { id:'dust_light', name:'Dust (Light)', cat:'texture', fx:{dust:20,grain:8} },
  { id:'dust_heavy', name:'Dust (Heavy)', cat:'texture', fx:{dust:50,grain:15,scratches:10} },
  { id:'scratches_light', name:'Scratches Light', cat:'texture', fx:{scratches:25} },
  { id:'scratches_heavy', name:'Scratches Heavy', cat:'texture', fx:{scratches:60,grain:10} },
  { id:'water_damage', name:'Water Damage', cat:'texture', fx:{blur:5,saturation:-15,brightness:-5,grain:20,vignette:20} },
  { id:'sun_faded', name:'Sun Faded', cat:'texture', fx:{brightness:15,saturation:-30,fade:25,temperature:10} },
  { id:'aged_photo', name:'Aged Photo', cat:'texture', fx:{saturation:-40,temperature:15,grain:25,dust:30,fade:20,vignette:15} },
  { id:'newspaper', name:'Newspaper Print', cat:'texture', fx:{saturation:-100,contrast:30,grain:5,dither:true,colorReduce:4} },
  { id:'xerox', name:'Xerox Copy', cat:'texture', fx:{saturation:-100,contrast:40,grain:15,brightness:5} },
  { id:'thermal_paper', name:'Thermal Receipt', cat:'texture', fx:{saturation:-100,contrast:25,brightness:10,fade:10} },
  { id:'crumpled_paper', name:'Crumpled Paper', cat:'texture', fx:{brightness:-5,contrast:10,grain:10,vignette:15,fade:5} },
  { id:'coffee_stain', name:'Coffee Stain', cat:'texture', fx:{temperature:15,tint:5,saturation:-10,fade:10,vignette:20} },
  { id:'moldy_film', name:'Moldy Film', cat:'texture', fx:{brightness:-10,contrast:20,saturation:-20,grain:40,dust:50} },
  
  // More Film Stocks
  { id:'kodak_portra_160vc', name:'Portra 160VC', cat:'film', fx:{brightness:5,contrast:12,saturation:20,temperature:5,grain:12} },
  { id:'kodak_portra_160nc', name:'Portra 160NC', cat:'film', fx:{brightness:8,contrast:3,saturation:-10,temperature:3,grain:8,fade:5} },
  { id:'fuji_400_pro', name:'Fuji 400 Pro', cat:'film', fx:{brightness:5,contrast:10,saturation:12,temperature:-10,tint:8,grain:15} },
  { id:'agfa_precisa', name:'Agfa Precisa 100', cat:'film', fx:{brightness:3,contrast:15,saturation:25,temperature:-5,grain:10} },
  { id:'lomochrome_metropolis', name:'Lomo Metropolis', cat:'film', fx:{brightness:-5,contrast:25,saturation:-30,temperature:-5,grain:20} },
  { id:'lomochrome_turquoise', name:'Lomo Turquoise', cat:'film', fx:{brightness:0,contrast:18,saturation:20,temperature:-40,tint:-30,grain:15} },
  { id:'kodak_vision3_250d', name:'Kodak Vision3 250D', cat:'film', fx:{brightness:5,contrast:10,saturation:10,temperature:5,grain:12} },
  { id:'kodak_vision3_500t', name:'Kodak Vision3 500T', cat:'film', fx:{brightness:-3,contrast:12,saturation:15,temperature:-20,grain:18} },
  { id:'fuji_eterna', name:'Fuji Eterna 250D', cat:'film', fx:{brightness:8,contrast:3,saturation:-10,temperature:0,grain:10,fade:12} },
  { id:'polaroid_600_fresh', name:'Polaroid 600 New', cat:'film', fx:{brightness:10,contrast:5,saturation:5,temperature:5,grain:5,vignette:8} },
  { id:'polaroid_600_old', name:'Polaroid 600 Expired', cat:'film', fx:{brightness:5,contrast:-5,saturation:-15,temperature:15,grain:25,fade:30,vignette:15} },
  { id:'instax_mini', name:'Instax Mini', cat:'film', fx:{brightness:12,contrast:8,saturation:10,temperature:8,grain:8,vignette:10} },

  // More 2000s Digital
  { id:'canon_ixus_v', name:'Canon IXUS V', cat:'2000s', fx:{brightness:5,contrast:10,saturation:22,sharpness:30,grain:5} },
  { id:'sony_dsc_f505', name:'Sony DSC-F505', cat:'2000s', fx:{brightness:3,contrast:15,saturation:18,sharpness:25,chromatic:10} },
  { id:'casio_exilim', name:'Casio Exilim', cat:'2000s', fx:{brightness:8,contrast:5,saturation:25,sharpness:20,pixelate:2} },
  { id:'panasonic_lumix_2003', name:'Lumix 2003', cat:'2000s', fx:{brightness:5,contrast:12,saturation:15,sharpness:35,temperature:-3} },
  { id:'samsung_digimax', name:'Samsung Digimax', cat:'2000s', fx:{brightness:10,contrast:3,saturation:20,sharpness:15,temperature:5} },
  { id:'hp_photosmart', name:'HP PhotoSmart', cat:'2000s', fx:{brightness:5,contrast:-5,saturation:10,sharpness:10,grain:12} },
  { id:'early_iphone', name:'iPhone 2G Camera', cat:'2000s', fx:{brightness:-5,contrast:5,saturation:-10,sharpness:-10,grain:20,blur:3} },
  { id:'blackberry_bold', name:'BlackBerry Bold', cat:'2000s', fx:{brightness:-10,contrast:15,saturation:-15,sharpness:20,grain:25,pixelate:3} },
  { id:'nokia_n95', name:'Nokia N95', cat:'2000s', fx:{brightness:5,contrast:12,saturation:15,sharpness:40,grain:8} },
  { id:'motorola_razr', name:'Motorola RAZR V3', cat:'2000s', fx:{brightness:-5,contrast:5,saturation:-25,sharpness:-20,grain:30,pixelate:8} },
  { id:'psp_camera', name:'PSP Camera', cat:'2000s', fx:{brightness:-8,contrast:5,saturation:-20,sharpness:-15,pixelate:10,grain:35} },
  { id:'dsi_camera', name:'Nintendo DSi', cat:'2000s', fx:{brightness:5,contrast:10,saturation:-10,sharpness:5,pixelate:12,grain:25} },

  // More Glitch / Artifacts
  { id:'moire_pattern', name:'Moiré Pattern', cat:'glitch', fx:{scanlines:95,brightness:5} },
  { id:'analog_interference', name:'Analog Noise', cat:'glitch', fx:{grain:95,brightness:-10,contrast:30,saturation:-100} },
  { id:'vhs_head_clog', name:'VHS Head Clog', cat:'glitch', fx:{blur:15,grain:50,scanlines:20,channelShift:15} },
  { id:'dvd_scratch', name:'DVD Scratch', cat:'glitch', fx:{datamosh:40,pixelate:5,channelShift:20} },
  { id:'low_bitrate_stream', name:'Low Bitrate 2007', cat:'glitch', fx:{jpegQ:8,pixelate:8,blur:3} },
  { id:'cctv_1995', name:'CCTV 1995', cat:'glitch', fx:{saturation:-100,contrast:50,brightness:20,grain:60,scanlines:40} },
  { id:'satellite_glitch', name:'Satellite Glitch', cat:'glitch', fx:{datamosh:90,channelShift:50,pixelate:15} },
  { id:'pixel_ghosting', name:'Pixel Ghosting', cat:'glitch', fx:{blur:10,channelShift:10,brightness:5} },
  { id:'dead_pixels', name:'Dead Pixels', cat:'glitch', fx:{dust:80,brightness:-5} },
  { id:'overclock_fail', name:'Overclock Fail', cat:'glitch', fx:{channelShift:80,contrast:50,pixelate:4} },
  { id:'magnetic_damage', name:'Magnetic Damage', cat:'glitch', fx:{channelShift:30,brightness:20,tint:20,vignette:40} },
  { id:'bit_flip', name:'Bit Flip Error', cat:'glitch', fx:{datamosh:60,pixelate:2,channelShift:10} },
  
  // More Color / Styles
  { id:'kodachrome_64', name:'Kodachrome 64', cat:'color', fx:{brightness:3,contrast:18,saturation:25,temperature:5,grain:5} },
  { id:'autochrome', name:'Autochrome', cat:'color', fx:{brightness:5,contrast:-5,saturation:-10,temperature:10,grain:60,fade:15} },
  { id:'technicolor_2', name:'Technicolor 2-Strip', cat:'color', fx:{brightness:5,contrast:25,saturation:40,temperature:5,tint:-10} },
  { id:'technicolor_3', name:'Technicolor 3-Strip', cat:'color', fx:{brightness:3,contrast:30,saturation:50} },
  { id:'high_key', name:'High Key Digital', cat:'color', fx:{brightness:40,contrast:-20,saturation:-10,fade:15} },
  { id:'low_key', name:'Low Key Digital', cat:'color', fx:{brightness:-40,contrast:30,saturation:-20,vignette:40} },
  { id:'vaporwave', name:'Vaporwave', cat:'color', fx:{brightness:10,contrast:10,saturation:40,temperature:-20,tint:30,halation:30} },
  { id:'cyberpunk', name:'Cyberpunk', cat:'color', fx:{brightness:-10,contrast:25,saturation:60,temperature:-30,tint:40,halation:50} },
  { id:'y2k_aesthetic', name:'Y2K Aesthetic', cat:'color', fx:{brightness:15,contrast:-10,saturation:15,temperature:-10,halation:40,fade:10} },
  { id:'liminal_space', name:'Liminal Space', cat:'color', fx:{brightness:-5,contrast:5,saturation:-15,grain:20,blur:3,vignette:20} },
  { id:'surreal_dream', name:'Surreal Dream', cat:'color', fx:{brightness:10,contrast:-15,saturation:30,blur:10,halation:60} },
  { id:'noir_digital', name:'Noir Digital', cat:'color', fx:{saturation:-100,contrast:60,brightness:-10,sharpness:30} },
  
  // More Lens
  { id:'macro_extension', name:'Macro Extension', cat:'lens', fx:{vignette:20,blur:15,sharpness:10} },
  { id:'dirty_lens', name:'Dirty Lens', cat:'lens', fx:{blur:5,brightness:10,contrast:-10,halation:40} },
  { id:'lens_smudge', name:'Fingerprint Smudge', cat:'lens', fx:{blur:12,contrast:-15,halation:50} },
  { id:'prism_rainbow', name:'Prism Rainbow', cat:'lens', fx:{channelShift:25,halation:20,brightness:5} },
  { id:'kaleidoscope_3', name:'Kaleidoscope 3', cat:'lens', fx:{fisheye:50,chromatic:20} },
  { id:'wide_angle_20mm', name:'20mm Wide Angle', cat:'lens', fx:{barrel:25,vignette:15} },
  { id:'telephoto_zoom', name:'Telephoto Zoom', cat:'lens', fx:{pincushion:20,blur:8} },
  { id:'broken_optics', name:'Broken Optics', cat:'lens', fx:{chromatic:50,blur:10,barrel:30} },
  
  // Custom categories or hybrids
  { id:'night_vision_gen2', name:'Night Vision G2', cat:'color', fx:{saturation:-100,temperature:-40,tint:80,brightness:30,grain:40,scanlines:15} },
  { id:'security_cam_80s', name:'Security Cam 80s', cat:'glitch', fx:{saturation:-100,contrast:30,brightness:10,grain:80,scanlines:60} },
  { id:'fax_machine', name:'Fax Machine', cat:'texture', fx:{saturation:-100,contrast:80,brightness:20,pixelate:2,dither:true,colorReduce:2} },
  { id:'halftone_print', name:'Halftone Print', cat:'texture', fx:{saturation:-100,contrast:40,pixelate:3,dither:true,colorReduce:4} },
  { id:'dot_matrix', name:'Dot Matrix', cat:'texture', fx:{saturation:-100,contrast:50,pixelate:4,scanlines:80} },
  { id:'gameboy_camera', name:'GameBoy Camera', cat:'2000s', fx:{saturation:-100,contrast:40,pixelate:6,colorReduce:4} },
  { id:'virtual_boy', name:'Virtual Boy', cat:'glitch', fx:{saturation:-100,tint:-100,contrast:50,brightness:-10,pixelate:4} },
  
  // Artifacts & Specialties
  { id:'leak_rainbow', name:'Rainbow Leak', cat:'lens', fx:{lightleak:90,chromatic:30,halation:20} },
  { id:'edge_glow', name:'Edge Glow', cat:'color', fx:{halation:90,brightness:5} },
  { id:'solarized', name:'Solarized', cat:'color', fx:{contrast:80,brightness:20,saturation:30} },
  { id:'neon_signs', name:'Neon Signs', cat:'color', fx:{saturation:80,halation:70,contrast:15} },
  { id:'under_exposure', name:'Deep Under', cat:'color', fx:{brightness:-60,contrast:40,vignette:60} },
  { id:'blown_out', name:'Blown Out', cat:'color', fx:{brightness:60,contrast:-20,fade:30} },
  { id:'damaged_negative', name:'Damaged Neg', cat:'texture', fx:{scratches:90,dust:90,grain:40,fade:15} },
  { id:'chemical_burn', name:'Chem Burn', cat:'texture', fx:{lightleak:100,temperature:40,tint:20,contrast:20} },
  { id:'radioactive', name:'Radioactive', cat:'color', fx:{temperature:-50,tint:100,brightness:20,halation:50} },
  { id:'acid_trip', name:'Acid Trip', cat:'glitch', fx:{channelShift:100,saturation:100,contrast:20} },
  { id:'pixel_rain', name:'Pixel Rain', cat:'glitch', fx:{pixelate:5,scanlines:30,channelShift:15} },
  { id:'analog_sunset', name:'Analog Sunset', cat:'color', fx:{temperature:50,tint:-20,saturation:30,vignette:30,fade:10} },
  { id:'midnight_city', name:'Midnight City', cat:'color', fx:{temperature:-30,brightness:-20,saturation:15,halation:40} },
  { id:'sepia_2000s', name:'Digital Sepia', cat:'2000s', fx:{saturation:-100,temperature:20,sharpness:20,grain:5} },
  { id:'polaroid_i_type', name:'Instax Square', cat:'film', fx:{brightness:5,contrast:10,saturation:8,temperature:5,vignette:12,fade:10} },
  { id:'kodak_e100', name:'Kodak E100', cat:'film', fx:{brightness:3,contrast:12,saturation:20,temperature:-5,grain:8} },
  { id:'fuji_astia', name:'Fuji Astia', cat:'film', fx:{brightness:8,contrast:5,saturation:-5,temperature:-3,grain:10,fade:5} },
];
